### ISSUE TITLE
Clipboard can't fetch data from the clipboard.

### ISSUE THREAD

**Issue by xyfll7** [nik3212/ClipboardManager#1]
Clipboard can't fetch data from the clipboard.
如果剪切板为空，就会一直打印这句话：
If the clipboard is empty, the sentence wii always be printed: "Clipboard can't fetch data from the clipboard."

**Comment by ns-vasilev** [comment]
@xyfll7 thanks! 

I will try to fix that as soon as possible.

**Comment by xyfll7** [comment]
Thank you very much. This is very important to me

**Comment by ns-vasilev** [comment]
@xyfll7 I updated the framework. Please, use version 1.0.1.

**Comment by xyfll7** [comment]
thanks!
